version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: mern-web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - node
    ports:
      - "80:80"
  node:
    container_name: mern-node
    build: docker/node
    working_dir: /application
    env_file: .env
    links:
      - mongo
    volumes:
      - .:/application
  mongo:
    image: mongo
    volumes:
      - ./docker/mongodb/data/:/data/db/
    ports:
      - "27017:27017"