version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: mern-web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    links:
      - node
    ports:
      - "80:80"
  node:
    container_name: mern-node
    build: docker/node
    working_dir: /application
    links:
      - mongo
    volumes:
      - ./backend:/application
    ports:
      - "9229:9229"
  react:
    image: node:12
    working_dir: /application
    volumes:
      - ./frontend:/application
  mongo:
    image: mongo
    volumes:
      - ./docker/mongodb/data/:/data/db/
    ports:
      - "27017:27017"
